### PR TITLE
Diversity

### PR DESCRIPTION
**Pull request by carlopacioni**
Hi there,
I started off with the intention of include SD estimates for mean values estimated at pop level (I do believe that a measure of its dispersion should accompany any average), but then I ended up picking up a few things along the way, so I briefly summarise them below. 
I have often left or commented out your code/objects (e.g. `nl`) and added my in parallel (e.g. `nltest`) so that it was easier to see the difference and also because I thought it was easier if you want to keep only part of my modifications but not all of them. Hence, this code will need some cleanup, which I’m happy to do if you think you are going to accept the pull request (sorry, just economising my time!). Note that I have not updated the doc and didn’t look at the code for the plot, so I’m not sure whether that needs to be modified based on the new code.

- `nl` (L168) calculates the number of loci without missing data. I don’t think that this is what the users are expecting. I think most people would expect the number of loci genotyped within each pop even if these have a small number of missing data (i.e. excluding only the ones where data are completely missing). This is what my `nltest` does. Either way, it may be good to explain the specifics in the function doc?

- `nInd` (L189) will fail for pops where Ho is 0, although samples exist. `ntest` (L184) explicitly quantifies n.

- Function doc says that `gl.report.heterozygosity` calculates unbiased expected heterozygosity, however, the code doesn’t correct for sample size as it should. I have now created an additional obj (`uHexp`) that does this. Note that this is corrected using the appropriate sample size for each locus. I think you should keep `Hexp` for comparison with previous results.

- `Ho.adj` and `He.adj` would not adjust estimates on a per locus basis (as I think it should), but used the total number of variant sites regardless as to whether all loci were genotyped for each pop. I have corrected this. 

- I have added the mean number of individuals genotyped across loci in the table output. I think this is a useful metric for users.

- There was a bug when `plot=FALSE`. That should be fixed now.

Cheers,
Carlo

### CODE REVIEW

**Comment by mijangos81** [comment]
Hi Carlo,

Thank you very much for contributing to dartR. Your fixes are very valuable indeed!
I have added them in the developing version of dartR (branch: "dev"), which you can check using the link below.
https://github.com/green-striped-gecko/dartR/blob/dev/R/gl.report.heterozygosity.r 

You can install this dev version by using:
devtools::install_github("green-striped-gecko/dartR@dev") 

Or you can just fork it.

In case you are interested in contributing to dartR further, we would be more than happy to acknowledge your contributions in a more "official" manner, I think Arthur and Bernd could extend more on this subject.

We have been also working on a tutorial for developers (attached), if you are curious. 

Cheers,
Luis 

[Tutorial_0_dartR_for_the_Developer_2.0.pdf](https://github.com/green-striped-gecko/dartR/files/7216028/Tutorial_0_dartR_for_the_Developer_2.0.pdf)

**Comment by carlopacioni** [comment]
Hi Luis,
good to hear from you. I'm happy you found my contribution useful. I have been working on a few additional things today. I'll see if I have a chance to get oriented on the dev branch and maybe push them there if this is more convenient. Don't close this pull request quite yet, though, just in case I end up pushing the changes here.

I'll try also to have a look at the pdf that you linked. 

I have a few projects where I'm using dart data and have a few scripts I think it may make sense to include in dartR. So, it is likely you will be hearing from more from me!

Ciao for now.
carlo

**Comment by biomatix** [comment]
This is the latest version.

A

**Comment by mijangos81** [comment]
Summary of changes in gl.report.heterozygosity:

- The total number of loci reported by the function is the number of loci that are not all NA's. Before the total number of loci was the number of loci without NA's. I modified Carlo's fix because it crashed when there were no loci with NA's.
- Unbiased heterozygosity was added and calculated in each locus using as sample size the number of alleles without missing data. 
- FIS (inbreeding coefficient) was added.
- The function gives the same results as genalex.
- The reference to Nei's paper was removed from the function's documentation because the function does not use exactly the same equations. Instead, the actual equations used in the function are shown in the documentation. 
- Standard deviation is calculated for all the statistics
- The plot for method="pop" was modified to show observed, expected heterozygosities and FIS in the same plot (see attached). 
- These changes have been merged into dev. 

[Rplot.pdf](https://github.com/green-striped-gecko/dartR/files/7230617/Rplot.pdf)

**Pull request closed without merging**
